all:
	g++ -O3 -g0 -w main.cpp ../System/Debug/viewer.cpp -lglut -lGL -lGLU -lxml2 -lfftw3 -lfftw3f -lboost_thread -lboost_system -I../System/InputOutput/ -I../System/Debug/ -I../System/MultiThreading/ -I../System/Networking/
