all:
	g++ -m64 -O3 -g0 -w -o ../bin/map_migration main.cpp ../System/Debug/viewer.cpp -lglut -lGL -lGLU -lxml2 -lfftw3 -lfftw3f -lboost_thread -lboost_system -I../System/InputOutput/ -I../System/LinearAlgebra/ -I../System/RayTracing/ -I../System/Debug/;
	#./script;
	#../bin/show ../Data/wave_propagation_data.SEP &
